# #
# # # def signup(request):
# # #     if request.method == 'POST':
# # #         username = request.POST['username']
# # #         # jeśli żadania mają metodę POST kiedy uzytkownik jej szuka lub do niej wejdzie, to jest wywoływana za pomocą metody POST
# # #         username = request.POST['username']
# # #         email = request.POST['email']
# # #         password = request.POST['password']
# # #         password2 = request.POST['password2']
# # #
# # #         if password == password2:
# # #             if User.objects.filter(email=email).exists():
# # #                 messages.info(request, 'Email taken')
# # #                 return redirect('signup')
# # #             elif User.objects.filter(username=username).exists():
# # #                 messages.info(request, 'Username taken')
# # #                 return redirect('signup')
# # #             else:
# # #                 user = User.objects.create_user(username=username, email=email, password=password)
# # #                 user.save()
# # #                 # log user in and redirect to settings page
# # #                 user_login = auth.authenticate(username=username, password=password)
# # #                 auth.login(request, user_login)
# # #                 # create a Profile object for the new user
# # #                 user_model = User.objects.get(username=username)
# # #                 new_profile = Profile.objects.create(user=user_model, id_user=user_model.id)
# # #                 new_profile.save()
# # #                 return redirect('signup')  # było settings
# # #
# # #
# # #         else:
# # #             messages.info(request, 'Password Not Matching')
# # #             return redirect('signup')
# # #     else:
# # #         return render(request, 'base.html')
# # #
# # #
# # # class SigninView(View):
# # #     def get(self, request):
# # #         if request.method == 'POST':
# # #             username = request.POST['username']
# # #             password = request.POST['password']
# # #
# # #             user = auth.authenticate(username=username, password=password)
# # #
# # #             if user is not None:
# # #                 auth.login(request, user)
# # #                 return redirect('/')
# # #             else:
# # #                 messages.info(request, ' Invalid')
# # #                 return redirect('signin')
# # #
# # #         else:
# # #             return render(request, 'register.html')
# #
# #
# # #
# # # Jeszcze poziomo było tak :
# # # <div class="parent">
# # #   <strong class="inline1">
# # #     <a class="nav-link active" href="{% url 'register' %}">Worker</a>
# # # </strong>
# # #   <strong class="inline2">inline 2</strong>
# # #
# # # </div>
# #
# #
# # # migrations 0007
# # # # Generated by Django 4.1.3 on 2022-12-07 11:17
# # #
# # # from django.db import migrations, models
# # # import django.db.models.deletion
# # #
# # #
# # # class Migration(migrations.Migration):
# # #
# # #     dependencies = [
# # #         ('people', '0006_person_alter_patient_patient_delete_profile_and_more'),
# # #     ]
# # #
# # #     operations = [
# # #         migrations.AlterField(
# # #             model_name='company',
# # #             name='profile_com',
# # #             field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# # #         ),
# # #         migrations.AlterField(
# # #             model_name='patient',
# # #             name='patient',
# # #             field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.company'),
# # #         ),
# # #         migrations.AlterField(
# # #             model_name='patient',
# # #             name='profile',
# # #             field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# # #         ),
# # #         migrations.AlterField(
# # #             model_name='specialist',
# # #             name='profile_spec',
# # #             field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# # #         ),
# # #     ]
# #
# #
# # migrations 0006
# # # Generated by Django 4.1.3 on 2022-12-07 11:10
# #
# # from django.db import migrations, models
# # import django.db.models.deletion
# # import uuid
# #
# #
# # class Migration(migrations.Migration):
# #
# #     dependencies = [
# #         ('people', '0005_remove_profile_id_user_alter_profile_id'),
# #     ]
# #
# #     operations = [
# #         migrations.CreateModel(
# #             name='Person',
# #             fields=[
# #                 ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
# #                 ('first_name', models.CharField(max_length=128)),
# #                 ('last_name', models.CharField(max_length=128)),
# #             ],
# #         ),
# #         migrations.AlterField(
# #             model_name='patient',
# #             name='patient',
# #             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.company'),
# #         ),
# #         migrations.DeleteModel(
# #             name='Profile',
# #         ),
# #         migrations.AddField(
# #             model_name='company',
# #             name='profile_com',
# #             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# #         ),
# #         migrations.AddField(
# #             model_name='patient',
# #             name='profile',
# #             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# #         ),
# #         migrations.AddField(
# #             model_name='specialist',
# #             name='profile_spec',
# #             field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
# #         ),
# #     ]
# #
# #
# # migracja 0005
# # # Generated by Django 4.1.3 on 2022-12-06 15:12
# #
# # from django.db import migrations, models
# # import uuid
# #
# #
# # class Migration(migrations.Migration):
# #
# #     dependencies = [
# #         ('people', '0004_remove_company_profile_com_remove_patient_profile_and_more'),
# #     ]
# #
# #     operations = [
# #         migrations.RemoveField(
# #             model_name='profile',
# #             name='id_user',
# #         ),
# #         migrations.AlterField(
# #             model_name='profile',
# #             name='id',
# #             field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
# #         ),
# #     ]
# #
# #
# # migracja 0004
# # # Generated by Django 4.1.3 on 2022-12-06 15:06
# #
# # from django.db import migrations, models
# # import django.db.models.deletion
# #
# #
# # class Migration(migrations.Migration):
# #
# #     dependencies = [
# #         ('people', '0003_remove_company_employee_remove_profile_password_and_more'),
# #     ]
# #
# #     operations = [
# #         migrations.RemoveField(
# #             model_name='company',
# #             name='profile_com',
# #         ),
# #         migrations.RemoveField(
# #             model_name='patient',
# #             name='profile',
# #         ),
# #         migrations.RemoveField(
# #             model_name='specialist',
# #             name='profile_spec',
# #         ),
# #         migrations.AddField(
# #             model_name='profile',
# #             name='company',
# #             field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='people.company'),
# #             preserve_default=False,
# #         ),
# #         migrations.AddField(
# #             model_name='profile',
# #             name='patient',
# #             field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='people.patient'),
# #             preserve_default=False,
# #         ),
# #         migrations.AddField(
# #             model_name='profile',
# #             name='profile_spec',
# #             field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='people.specialist'),
# #             preserve_default=False,
# #         ),
# #     ]
#
#
# migracja 0003
# # Generated by Django 4.1.3 on 2022-12-05 21:20
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('people', '0002_rename_nemployee_company_employee'),
#     ]
#
#     operations = [
#         migrations.RemoveField(
#             model_name='company',
#             name='employee',
#         ),
#         migrations.RemoveField(
#             model_name='profile',
#             name='password',
#         ),
#         migrations.AddField(
#             model_name='company',
#             name='no_employee',
#             field=models.IntegerField(default=False),
#             preserve_default=False,
#         ),
#     ]
#
#
# migracja 0002
# # Generated by Django 4.1.3 on 2022-12-05 13:08
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('people', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.RenameField(
#             model_name='company',
#             old_name='nemployee',
#             new_name='employee',
#         ),
#     ]
