# Generated by Django 4.1.3 on 2022-12-02 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=256)),
                ('industry', models.CharField(max_length=128)),
                ('nemployee', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(default=True, max_length=28)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128)),
                ('specialization', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('profile_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('learned_profession', models.CharField(max_length=128)),
                ('work_done', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.company')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.profile')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='profile_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.profile'),
        ),
    ]
