# Generated by Django 4.1.3 on 2022-12-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='time',
            new_name='what_time',
        ),
    ]
