# Generated by Django 4.1.3 on 2022-12-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='what_time',
            field=models.DateTimeField(),
        ),
    ]
