# Generated by Django 4.1.3 on 2022-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_person_remove_company_nemployee_company_no_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='profile',
            new_name='your_name',
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
