# Generated by Django 4.1.3 on 2022-12-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_release_author_specialist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0004_alter_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='profile_spec',
        ),
        migrations.RemoveField(
            model_name='company',
            name='no_employee',
        ),
        migrations.RemoveField(
            model_name='company',
            name='profile_com',
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
        migrations.AddField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.company'),
        ),
        migrations.AddField(
            model_name='visit',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
