# Generated by Django 4.1.3 on 2022-12-02 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full2name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('no_edition', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, ''), (1, '*    '), (2, '**   '), (3, '***  '), (4, '**** '), (5, '*****')])),
                ('autors', models.ManyToManyField(to='media.autor')),
                ('kategoris', models.ManyToManyField(to='media.category')),
            ],
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('opinion', models.IntegerField(choices=[(0, ''), (1, '*    '), (2, '**   '), (3, '***  '), (4, '**** '), (5, '*****')])),
                ('autors', models.ManyToManyField(to='media.autor')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.book')),
                ('kateg', models.ManyToManyField(to='media.category')),
            ],
        ),
    ]
