# Generated by Django 4.1.3 on 2022-12-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_id'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author_specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.specialist')),
                ('category_release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.category')),
            ],
        ),
    ]
