# Generated by Django 4.1.3 on 2022-12-08 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='author_specialist',
        ),
    ]
