# Generated by Django 4.1.3 on 2022-12-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
