# Generated by Django 4.1.3 on 2022-12-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_release_author_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='opinion',
        ),
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='autors',
            field=models.ManyToManyField(related_name='audiobooks', to='media.autor'),
        ),
    ]
