# Generated by Django 4.1.3 on 2022-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_book_authors_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='relimg',
            field=models.ImageField(default='test.png', upload_to='profile_images'),
        ),
    ]
