# Generated by Django 4.1.3 on 2022-12-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_audiobook_opinion_remove_book_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='kateg',
            new_name='kategoris',
        ),
        migrations.AddField(
            model_name='release',
            name='relimg',
            field=models.ImageField(default='new_post.png', upload_to='profile_images'),
        ),
    ]
