# Generated by Django 4.1.3 on 2022-12-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_kateg_audiobook_kategoris_release_relimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='no_edition',
        ),
    ]
