# Generated by Django 4.1.3 on 2022-12-09 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0006_remove_book_no_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='author_specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
