# Generated by Django 4.1.3 on 2022-12-09 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_release_author_specialist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='full2name',
            new_name='fullname',
        ),
    ]
